#!/bin/sh

ENVIRONMENT_VALIABLE_SYSTEM_WIDE_FILENAME=/etc/environment

echo
echo
echo

echo ENVIRONMENT_VALIABLE_SYSTEM_WIDE_FILENAME:$ENVIRONMENT_VALIABLE_SYSTEM_WIDE_FILENAME.

. $ENVIRONMENT_VALIABLE_SYSTEM_WIDE_FILENAME
