#!/bin/bash 

VAGRANT_USER=vagrant
ORACLE_USER=oracle
ORACLE_INSTALL_GROUP=oinstall
ORACLE_INSTAL_FOLDER=/opt/oracle
WEBLOGIC_INSTALL_FOLDER=$ORACLE_INSTAL_FOLDER/weblogic

export MW_HOME=$WEBLOGIC_INSTALL_FOLDER
export WLS_HOME=$WEBLOGIC_INSTALL_FOLDER/wlserver
export WL_HOME=$WEBLOGIC_INSTALL_FOLDER/wlserver

sudo groupadd -g 1000 $ORACLE_INSTALL_GROUP
sudo groupadd -g $ORACLE_INSTALL_GROUP
sudo useradd -u 1100 -g $ORACLE_INSTALL_GROUP $ORACLE_USER
sudo passwd $ORACLE_USER
sudo usermod -a -G $ORACLE_INSTALL_GROUP $VAGRANT_USER

sudo chown -R $ORACLE_USER:$ORACLE_INSTALL_GROUP ORACLE_INSTAL_FOLDER
sudo chmod -R 775 ORACLE_INSTAL_FOLDER/