ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "postgres"
    d.name = "postgres"
    d.ports = [ "5432:5432" ]
    d.env = {
        POSTGRES_USER: "rnr",
        POSTGRES_PASSWORD: "rnr",
      }
  end
  config.vm.provision "docker" do |d|
    d.run "docker-entrypoint.sh",
      cmd: "docker-entrypoint.sh postgres"
      #args: "-v '/vagrant:/var/www'"
      #daemonize: true
    #d.remains_running = true
  end
end
