# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.provision "docker"
  config.vm.network "forwarded_port", guest: 1521, host: 1521

  config.vm.network "private_network", :type => 'dhcp', :adapter => 2

  config.vm.synced_folder "../../data/oracle/oradata", "/oradata"
  config.vm.synced_folder "../../software", "/software"
 
  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker_host_ubuntu_geerlingguy-ubuntu1604"
  
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
 
  config.vm.provision "shell", path: "provision.sh"
end
